import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../context/theme-provider";
import { UserProvider } from "../context/user-context"
import { WorkoutProvider } from "../context/workout-context"
import DynamicFavicon from "./components/DynamicFavicon";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "fitness-app",
  description: "Generated by fitness-app",
  icons: {
    icon: [
      {
        url: "/fitness-app-v1.ico",
        media: "(prefers-color-scheme: dark)",
        rel: "icon",
        type: "image/x-icon",
      },

    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // console.log("ROOT LAYOUT:: pathname", pathname);

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <UserProvider>
          <WorkoutProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <DynamicFavicon />
              {children}
            </ThemeProvider>
          </WorkoutProvider>
        </UserProvider>
      </body>
    </html >
  );
}
